--liquibase formatted sql
--changeset username:crear_tabla_clientes
CREATE TABLE clientes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100),
  correo VARCHAR2(150)
);
